import 'dart:math';

final List<String> splashTexts = [
  "Watt was that?",
  "Shocking!",
  "Have fun, darnit!",
  "Red Alliance!",
  "Blue Alliance!",
  "RIP Dodo",
  "RIP Komo",
  "RIP Ampharos",
  "No comms? 🤨",
  "Electric!",
  "Hey there, pay attention!",
  "Shift + Alt + F your pit",
  "Who are we? MC^2",
  "kg m^2/s^2 is a unit of 948",
  "Not by the wires!",
  "Have you turned it off and on again?",
  "The only thing I can pull are my commits",
  "Red and Gold!",
  "FIRE IN THE HOLE",
  "Is there a sugar free version?",
  "If there are joysticks, are there sadsticks?",
  "Wisconsin approved",
  "Drop that like and leave a comment below",
  "It's not a bug, it's a feature!",
  "W IT",
  "Don't fall!",
  "Build a turret, they said",
  "Well... as long as it works",
  "Dart? Well, it actually builds quite slowly",
  "Programmer? I'm glad you support proper English",
  "Zero factor authentication",
  "Accept cookies? \\(•ω•`)o",
  "error 1002: ; Expected",
  "\"I think political comments are the best thing to put on splash texts.\" -- Krish",
  "Now with 95% less consistent variable names!",
  "Can you hear the music?",
  "Also try Terraria!",
  "\${configData[\"scouterName\"]} is you!",
  "\"It'll be fine\" Famous last words",
  "ong frfr",
  "\\\\TODO: Come up with more splash texts",
  "Bring back build season mac n' cheese",
  "Is the sistine chapel cool",
  "Made with smiles and enriched wheat flour",
  "\"I lowkey forgot miami was a city\" - Cad VP",
  "All the stars!",
  "Bombardino Crocodilo",
  "BOO! Did I scare ya?",
  "Shoutout to 1778, they're pretty chill",
  "The 2-year curse is real",
  "#r4nd0m",
  "WE LOVE DRIVE TEAM",
  "colin was here :3",
  "Gray screen of death (>_<)"
];

String randomSplashText() {
  return splashTexts[Random().nextInt(splashTexts.length)];
}
